#!/bin/bash
killall dzen2 &
killall conky &

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-t spawn urxvt
hc keybind XF86AudioLowerVolume spawn ~/.config/herbstluftwm/volume.sh down
hc keybind XF86AudioRaiseVolume spawn ~/.config/herbstluftwm/volume.sh up
hc keybind XF86AudioMute spawn ~/.config/herbstluftwm/volume.sh mute

# tags
TAG_NAMES=( term)
TAG_KEYS=( term )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-Right use_index +1 --skip-visible
hc keybind $Mod-Left  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.01
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

#Screenshot
hc keybind Print spawn ~/.config/herbstluftwm/screenshot.sh

#Dmenu
hc keybind $Mod-F2 spawn dmenu_run -b -i #-nb '#729FCF' -nf '#888888' -sb '#FFFF84' -sf '#1e1e1e'

# colors
hc set frame_border_active_color '#000000'
hc set frame_border_normal_color '#000000'
hc set frame_bg_normal_color '#000000'
hc set frame_bg_active_color '#000000'
hc set frame_active_opacity 60
hc set frame_normal_opacity 60
hc set frame_border_width 4
hc set window_border_width 0
hc set window_border_inner_width 0
hc set window_border_normal_color '#000000'
hc set window_border_active_color '#000000'
hc set frame_gap 8
hc set always_show_frame 1
hc set frame_bg_transparent 0
# add overlapping window borders
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

#rules
hc unrule -F
hc rule focus=off # normally do not focus new clients
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule class~'Steam' tag=steam
hc rule class~'Thunderbird' tag=mail
hc rule class~'Vlc' tag=vlc
hc rule instance=Dialog pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule title=ConkyFloatGraphs manage⁼off
hc rule title=mplayer-video tag=video focus=off
hc rule title=mplayer-video-ext tag=streamext focus=off fullscreen=on
hc rule title=mplayer-video-tv tag=streamtv focus=off fullscreen=on
hc rule title=vlc-video-float tag=video focus=off
hc rule title=vlctv tag=tv focus=off fullscreen=on
hc rule title=vlcext tag=vlcvideoext focus=on fullscreen=on
hc rule title=twitter-float tag=twitter focus=off
hc rule title=tvterm tag=tv focus=off
hc rule title=extterm tag=ext focus=off
hc rule title=plugin-container fullscreen=on focus=on

#tree
herbstclient set tree_style '╾│ ├└╼─┐'

#monitors
hc set_monitors 1920x1080+0+0
hc pad 0 25 343 25 0

hc add twitter
hc add_monitor 352x1030+1568+25 twitter maintwitter
hc lock_tag maintwitter

#other reals monitors

#hc add ext
#hc add_monitor 1366x768+1920+0 ext mainext
#hc pad mainext 0 0 25 0

#hc add tv
#hc add_monitor 1920x1080+3286+0 tv maintv
#hc pad maintv 0 0 25 0


#panels

#conky panel
panel=~/.config/herbstluftwm/panel.sh
$panel 0

#list app panel
panel2=~/.config/herbstluftwm/panel2.sh
$panel2 0

#others real monitors panels

#panel3=~/.config/herbstluftwm/panel3.sh
#$panel3 3

#panel4=~/.config/herbstluftwm/panel4.sh
#$panel4 4

#transparency panels
sleep 1 &&
exec `(transset-df .8 -n dzentop >/dev/null 2>&1 &)` &
sleep 1 &&
exec `(transset-df .8 -n dzenbottom >/dev/null 2>&1 &)` &

#sleep 1 &&
#exec `(transset-df .8 -n dzentv >/dev/null 2>&1 &)` &
#sleep 1 &&
#exec `(transset-df .8 -n dzenext >/dev/null 2>&1 &)` &
