#!/bin/bash
exec /home/oxhak/Scripts/ConkyWeather.sh &
killall compton &
killall conky &
feh --bg-fill  ~/Images/wallpaper.png &
killall dzen2 &

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#000000'
hsetroot -solid '#000000'

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-t spawn urxvt
hc keybind XF86AudioLowerVolume spawn ~/.config/herbstluftwm/volume.sh down
hc keybind XF86AudioRaiseVolume spawn ~/.config/herbstluftwm/volume.sh up
hc keybind XF86AudioMute spawn ~/.config/herbstluftwm/volume.sh mute

# tags
TAG_NAMES=( term)
TAG_KEYS=( term )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-Right use_index +1 --skip-visible
hc keybind $Mod-Left  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.01
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

#Screenshot 
hc keybind Print spawn ~/.config/herbstluftwm/screenshot.sh

#Dmenu
hc keybind $Mod-F2 spawn dmenu_run -b -i #-nb '#729FCF' -nf '#888888' -sb '#FFFF84' -sf '#1e1e1e'

# colors
hc set frame_border_active_color '#495d6e'
hc set frame_border_normal_color '#495d6e'
hc set frame_bg_normal_color '#0A0A0A'
hc set frame_bg_active_color '#0A0A0A'
hc set frame_active_opacity 100
hc set frame_normal_opacity 100
hc set frame_border_width 4
hc set window_border_width 0
hc set window_border_inner_width 0
hc set window_border_normal_color '#495d6e'
hc set window_border_active_color '#495d6e'
hc set frame_gap 8
hc set always_show_frame 1
hc set frame_bg_transparent 0
# add overlapping window borders 
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0


# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
#hc rule class=Vlc tag=1..20
hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
#hc rule class~'Firefox' tag=1
hc rule class~'Steam' tag=steam
hc rule class~'Thunderbird' tag=mail
hc rule class~'Vlc' tag=vlc
#hc rule class~'Vlc' tag=video
#hc rule class~'Conky' tag=visible
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on pseudotile=on
#hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' manage=off
#hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
#hc rule title=vlc-video-float manage=off class=MPlayer tag=visible
#hc rule title=conkyfloat tag=test

hc rule title=ConkyFloatGraphs manage⁼off

#hc rule title='Popcorn Time' tag=video focus=off
hc rule title=vlc-video-float tag=video focus=off
hc rule title=twitter-float tag=twitter focus=off
hc rule class~'ProjectM-pulseaudio' tag=video

# unlock, just to be sure
#hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
#hc detect_monitors
#hc set_monitors 1920x1080+0+0 1920x1080+0+0 
hc set_monitors 1920x1080+0+0 1920x1080+0+0 1920x1080+0+0 

hc chain , add video
hc focus_monitor 1
hc use video
hc lock_tag video

hc chain , add twitter
hc focus_monitor 2
hc use twitter
hc lock_tag twitter

hc focus_monitor 0
hc use term

# find the panel
#herbstclient pad $(herbstclient list_monitors | cut -d: -f1) 80 460 0 0;
#herbstclient pad 0 40 0 45 0;
herbstclient pad 0 17 338 17 -6;
herbstclient pad 1 17 -6 854 1573;
herbstclient pad 2 217 -6 17 1573;

panel=~/.config/herbstluftwm/panel.sh
$panel 0 &
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
 #for monitor in  $(herbstclient list_monitors | cut -d: -f1); do
     # start it on each monitor
 #   $panel $monitor &
#done

#panel2=~/.config/herbstluftwm/panel2.sh
#[ -x "$panel2" ] || panel=/etc/xdg/herbstluftwm/panel.sh
 #for monitor in  $(herbstclient list_monitors | cut -d: -f1); do
     # start it on each monitor
  #       $panel2 $monitor &
 #done
panel2=~/.config/herbstluftwm/panel2.sh
$panel2 0 &

sleep 1
compton --backend glx --vsync opengl &
#conky -c /home/oxhak/.conky/horloge &
#transset-df .8 -n dzenbottom &
#transset-df .8 -n dzentop &
